# Generated by Django 4.2.20 on 2025-12-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfiguration',
            name='name',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('adzuna', 'Adzuna'), ('brightermonday', 'BrighterMonday'), ('ajira', 'Ajira Portal')], max_length=50, unique=True, verbose_name='API Name'),
        ),
    ]
