# Generated by Django 4.2.20 on 2025-12-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_apiconfiguration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved by Admin'),
        ),
    ]
