# Generated by Django 4.2.20 on 2026-01-08 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_job_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='UserJobApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved to post visible jobs')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('reason', models.TextField(blank=True, verbose_name='Approval Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Job Approval',
                'verbose_name_plural': 'User Job Approvals',
            },
        ),
    ]
