# Generated by Django 4.2.20 on 2026-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_posting_type',
            field=models.CharField(choices=[('internal', 'Apply on Chuosmart'), ('external', 'External Link')], default='internal', help_text='Whether users apply via Chuosmart or are directed to an external site', max_length=20, verbose_name='Job Posting Type'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='jobs/documents/', verbose_name='Additional Documents'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='availability',
            field=models.CharField(blank=True, max_length=100, verbose_name='Availability'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Portfolio URL'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_expectation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salary Expectation (TZS)'),
        ),
    ]
