# Generated by Django 4.2.20 on 2026-06-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobcourserecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcourserecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobcourserecommendation',
            name='source',
            field=models.CharField(choices=[('cerebras', 'Cerebras AI'), ('fallback', 'Fallback')], default='', max_length=20, verbose_name='Recommendation source'),
        ),
    ]
