# Generated by Django 5.0.6 on 2025-03-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='banner_images')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(choices=[('Ardhi University', 'Ardhi University'), ('Arusha Technical College', 'Arusha Technical College'), ('Dar es Salaam Institute of Technology', 'Dar es Salaam Institute of Technology'), ('Institute of Finance Management (IFM)', 'Institute of Finance Management (IFM)'), ('International Medical and Technological University', 'International Medical and Technological University'), ('Kampala International University in Tanzania', 'Kampala International University in Tanzania'), ('Mount Meru University', 'Mount Meru University'), ('Muhimbili University of Health and Allied Sciences', 'Muhimbili University of Health and Allied Sciences'), ('Mzumbe University', 'Mzumbe University'), ('Nelson Mandela African Institute of Science and Technology', 'Nelson Mandela African Institute of Science and Technology'), ('Open University of Tanzania', 'Open University of Tanzania'), ('Sokoine University of Agriculture', 'Sokoine University of Agriculture'), ('St. Augustine University of Tanzania', 'St. Augustine University of Tanzania'), ('Tumaini University Makumira', 'Tumaini University Makumira'), ('University of Dar es Salaam', 'University of Dar es Salaam'), ('University of Dodoma', 'University of Dodoma')], max_length=200)),
                ('college', models.CharField(choices=[('School of Architecture, Construction Economics and Management', 'School of Architecture, Construction Economics and Management'), ('School of Earth Sciences, Real Estates, Business and Informatics', 'School of Earth Sciences, Real Estates, Business and Informatics'), ('School of Environmental Science and Technology', 'School of Environmental Science and Technology'), ('School of Spatial Planning and Social Sciences', 'School of Spatial Planning and Social Sciences'), ('School of Engineering', 'School of Engineering'), ('School of Business and Management', 'School of Business and Management'), ('School of Information and Communication Technology', 'School of Information and Communication Technology'), ('School of Engineering', 'School of Engineering'), ('School of Business and Management', 'School of Business and Management'), ('School of Information and Communication Technology', 'School of Information and Communication Technology'), ('Faculty of Accounting, Banking and Finance', 'Faculty of Accounting, Banking and Finance'), ('Faculty of Computing, Information Systems and Mathematics', 'Faculty of Computing, Information Systems and Mathematics'), ('Faculty of Economics and Management Sciences', 'Faculty of Economics and Management Sciences'), ('Faculty of Insurance and Social Protection', 'Faculty of Insurance and Social Protection'), ('Faculty of Medicine', 'Faculty of Medicine'), ('Faculty of Nursing', 'Faculty of Nursing'), ('Faculty of Medical Laboratory Sciences', 'Faculty of Medical Laboratory Sciences'), ('School of Health Sciences', 'School of Health Sciences'), ('School of Education', 'School of Education'), ('School of Business and Management', 'School of Business and Management'), ('Faculty of Theology', 'Faculty of Theology'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Business Studies', 'Faculty of Business Studies'), ('School of Medicine', 'School of Medicine'), ('School of Dentistry', 'School of Dentistry'), ('School of Pharmacy', 'School of Pharmacy'), ('School of Nursing', 'School of Nursing'), ('School of Public Health and Social Sciences', 'School of Public Health and Social Sciences'), ('School of Public Administration and Management', 'School of Public Administration and Management'), ('School of Business', 'School of Business'), ('School of Law', 'School of Law'), ('School of Public Administration and Management', 'School of Public Administration and Management'), ('School of Life Sciences and Bioengineering', 'School of Life Sciences and Bioengineering'), ('School of Computational and Communication Science and Engineering', 'School of Computational and Communication Science and Engineering'), ('School of Materials, Energy, Water and Environmental Sciences', 'School of Materials, Energy, Water and Environmental Sciences'), ('School of Business Studies and Humanities', 'School of Business Studies and Humanities'), ('Faculty of Arts and Social Sciences', 'Faculty of Arts and Social Sciences'), ('Faculty of Business Management', 'Faculty of Business Management'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Science, Technology and Environmental Studies', 'Faculty of Science, Technology and Environmental Studies'), ('College of Agriculture', 'College of Agriculture'), ('College of Forestry, Wildlife and Tourism', 'College of Forestry, Wildlife and Tourism'), ('College of Veterinary Medicine and Biomedical Sciences', 'College of Veterinary Medicine and Biomedical Sciences'), ('College of Social Sciences and Humanities', 'College of Social Sciences and Humanities'), ('Faculty of Social Sciences and Communication', 'Faculty of Social Sciences and Communication'), ('Faculty of Business Administration', 'Faculty of Business Administration'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Engineering', 'Faculty of Engineering'), ('Faculty of Theology', 'Faculty of Theology'), ('Faculty of Law', 'Faculty of Law'), ('Faculty of Education', 'Faculty of Education'), ('Faculty of Humanities and Social Sciences', 'Faculty of Humanities and Social Sciences'), ('Faculty of Business and Economics', 'Faculty of Business and Economics'), ('College of Engineering and Technology', 'College of Engineering and Technology'), ('College of Natural and Applied Sciences', 'College of Natural and Applied Sciences'), ('University of Dar es Salaam Business School', 'University of Dar es Salaam Business School'), ('College of Social Sciences', 'College of Social Sciences'), ('College of Humanities', 'College of Humanities'), ('College of Agricultural Sciences and Fisheries Technology', 'College of Agricultural Sciences and Fisheries Technology'), ('College of Humanities and Social Sciences', 'College of Humanities and Social Sciences'), ('College of Informatics and Virtual Education', 'College of Informatics and Virtual Education'), ('College of Natural and Mathematical Sciences', 'College of Natural and Mathematical Sciences'), ('College of Education', 'College of Education'), ('College of Health and Allied Sciences', 'College of Health and Allied Sciences'), ('College of Earth Sciences', 'College of Earth Sciences'), ('College of Business Studies and Law', 'College of Business Studies and Law')], max_length=200)),
                ('block_number', models.CharField(max_length=200, null=True)),
                ('room_number', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('M', 'Mobiles'), ('El', 'Electronics'), ('B', 'Books'), ('C', 'Clothing'), ('AC', 'Accessories')], max_length=2)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('On The Way', 'On The Way'), ('Received', 'Received'), ('Paid', 'Paid')], default='Pending', max_length=200)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
