# Generated by Django 5.0.6 on 2025-03-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.customer'),
            preserve_default=False,
        ),
    ]
