# Generated by Django 5.0.6 on 2025-03-12 07:59

import django.db.models.deletion
from django.db import migrations, models


def add_customer_with_check(apps, schema_editor):
    """
    Custom migration function to add customer field to products
    only if the referenced customer exists
    """
    Customer = apps.get_model('core', 'Customer')
    Product = apps.get_model('core', 'Product')
    
    # Check if customer with ID 5 exists
    if Customer.objects.filter(id=5).exists():
        # Only update products if customer exists
        for product in Product.objects.all():
            product.customer_id = 5
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.customer'),
        ),
        migrations.RunPython(add_customer_with_check, migrations.RunPython.noop),
    ]
