# Generated by Django 5.0.6 on 2025-03-12 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
