# Generated by Django 5.0.6 on 2025-03-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blog_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Free', 'Free'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], default='Free', max_length=10)),
                ('price', models.FloatField()),
                ('benefits', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscription'),
        ),
    ]
