# Generated by Django 5.0.6 on 2025-03-22 06:43

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_subscription_customer_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription',
            field=models.ForeignKey(blank=True, default=core.models.Customer.get_default_subscription, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscription'),
        ),
    ]
