# Generated by Django 4.2.20 on 2025-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobiles'), ('El', 'Electronics'), ('B', 'Books'), ('C', 'Clothing'), ('AC', 'Accessories'), ('S', 'Services')], max_length=2),
        ),
    ]
