# Generated by Django 4.2.20 on 2025-06-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='block_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='room_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
