# Generated by Django 4.2.20 on 2025-07-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_newslettersubscriber'),
        ('core', 'webp_migration'),
    ]

    operations = [
    ]
