# Generated by Django 4.2.20 on 2025-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0014_newslettersubscriber_webp_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/webp'),
        ),
    ]
