# Generated by Django 4.2.20 on 2025-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_markdown',
            field=models.BooleanField(default=True, help_text='Whether content is written in Markdown format'),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/webp'),
        ),
    ]
