# Generated by Django 4.2.20 on 2025-07-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ensure_all_products_have_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
