# Generated by Django 4.2.20 on 2025-07-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_markdown',
            field=models.BooleanField(default=False, help_text='Whether content is written in Markdown format'),
        ),
    ]
