# Generated by Django 4.2.20 on 2026-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_charset_collation_and_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail_cloudinary',
            field=models.CharField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='upload_method',
            field=models.CharField(choices=[('local', 'Local Storage (Device)'), ('cloudinary', 'Cloudinary (Cloud Storage)')], default='local', help_text='Method used to upload the thumbnail image', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Local image storage', null=True, upload_to='blog_thumbnails'),
        ),
    ]
