# Generated by Django 4.2.20 on 2026-06-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_sentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTestSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('categories', models.CharField(help_text='Comma-separated categories selected', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Test Send',
                'verbose_name_plural': 'Newsletter Test Sends',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=254)),
                ('sent_date', models.DateField()),
                ('categories', models.CharField(blank=True, help_text='Comma-separated list of categories included', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=20)),
            ],
            options={
                'verbose_name': 'Newsletter Send Log',
                'verbose_name_plural': 'Newsletter Send Logs',
                'unique_together': {('subscriber_email', 'sent_date')},
            },
        ),
    ]
