# Generated by Django 4.2.20 on 2025-07-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignup',
            name='purpose',
            field=models.CharField(default='enrolling in the digital marketing course', max_length=255),
        ),
    ]
