# Generated by Django 4.2.20 on 2026-08-16 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('software_url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('software', 'Software'), ('developer_tools', 'Developer Tools'), ('education', 'Education'), ('productivity', 'Productivity'), ('design', 'Design'), ('ai_tools', 'AI Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='materials_m_created_739a0f_idx'), models.Index(fields=['is_active', '-created_at'], name='materials_m_is_acti_06eb18_idx')],
            },
        ),
    ]
