# Generated by Django 4.2.20 on 2025-07-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_instructorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.coursecontent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lmsprofile')),
            ],
            options={
                'ordering': ['-accessed_at'],
                'unique_together': {('student', 'content')},
            },
        ),
    ]
