# Generated by Django 4.2.20 on 2025-07-06 08:53

from django.db import migrations


def create_initial_site_settings(apps, schema_editor):
    """
    Create the initial SiteSettings instance if it doesn't exist
    """
    SiteSettings = apps.get_model('lms', 'SiteSettings')
    if not SiteSettings.objects.exists():
        SiteSettings.objects.create(
            show_ads_before_free_courses=True
        )


def remove_initial_site_settings(apps, schema_editor):
    """
    Remove the initial SiteSettings instance (for reverse migration)
    """
    SiteSettings = apps.get_model('lms', 'SiteSettings')
    SiteSettings.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_sitesettings'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_site_settings,
            remove_initial_site_settings
        ),
    ]
