# Generated by Django 4.2.20 on 2025-07-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_create_initial_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('university', 'University Course'), ('general', 'General Course')], default='university', help_text='University courses require academic fields like course code, program, etc.', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text='Required for university courses only', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(blank=True, default=3, help_text='Required for university courses only', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_elective',
            field=models.BooleanField(default=False, help_text='Applies to university courses only'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6')], help_text='Required for university courses only', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Required for university courses only', null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], help_text='Required for university courses only', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], default=1, help_text='Required for university courses only', null=True),
        ),
    ]
