# Generated by Django 4.2.20 on 2025-07-08 07:37

from django.db import migrations


def ensure_site_settings(apps, schema_editor):
    """
    Make sure SiteSettings exists with ads enabled
    """
    SiteSettings = apps.get_model('lms', 'SiteSettings')
    settings, created = SiteSettings.objects.get_or_create(
        pk=1,
        defaults={'show_ads_before_free_courses': True}
    )
    
    # If settings already existed but ads are disabled, enable them
    if not created and not settings.show_ads_before_free_courses:
        settings.show_ads_before_free_courses = True
        settings.save()


def reverse_func(apps, schema_editor):
    """
    Reverse function (does nothing in this case)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_increase_slug_length'),
    ]

    operations = [
        migrations.RunPython(ensure_site_settings, reverse_func),
    ]
