# Generated by Django 4.2.20 on 2025-07-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_paymentmethod_courseenrollment_payment_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor who accepts this payment method', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='lms.lmsprofile'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_number',
            field=models.CharField(blank=True, default='N/A', help_text='Payment number or account (e.g. phone number, bank account)', max_length=100),
        ),
    ]
