# Generated by Django 4.2.20 on 2025-07-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_remove_paymentmethod_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this course at the top of listings'),
        ),
    ]
