# Generated by Django 4.2.20 on 2025-07-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_course_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for paid course', max_digits=10),
        ),
    ]
