# Generated by Django 4.2.20 on 2026-02-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_coursemodule_description_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Detailed course description and content'),
        ),
        migrations.AlterField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Brief summary of the course'),
        ),
    ]
