# Generated by Django 4.2.20 on 2026-05-26 08:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0018_sitesettings_show_list_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('organization_name', models.CharField(default='ChuoSmart Academy', max_length=255)),
                ('instructor_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('template_style', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('academic', 'Academic'), ('corporate', 'Corporate')], default='modern', max_length=50)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=20)),
                ('primary_color', models.CharField(default='#1E40AF', max_length=20)),
                ('secondary_color', models.CharField(default='#111827', max_length=20)),
                ('accent_color', models.CharField(default='#D97706', max_length=20)),
                ('background_style', models.CharField(choices=[('plain', 'Plain'), ('gradient', 'Gradient'), ('bordered', 'Bordered'), ('watermark', 'Watermark')], default='plain', max_length=50)),
                ('border_style', models.CharField(choices=[('none', 'None'), ('thin', 'Thin'), ('double', 'Double'), ('premium', 'Premium Frame')], default='premium', max_length=50)),
                ('font_style', models.CharField(choices=[('serif', 'Serif'), ('sans', 'Sans Serif'), ('modern', 'Modern'), ('academic', 'Academic')], default='serif', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='certificates/logos/')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='certificates/signatures/')),
                ('seal_image', models.ImageField(blank=True, null=True, upload_to='certificates/seals/')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='certificates/watermarks/')),
                ('certificate_body', models.TextField(blank=True, default='This certificate is proudly presented to {{ student_name }} for successfully completing {{ course_title }} on {{ completion_date }}.')),
                ('recipient_name_format', models.CharField(default='{{ student_name }}', max_length=100)),
                ('course_name_display', models.CharField(default='{{ course_title }}', max_length=150)),
                ('completion_date_display', models.CharField(default='{{ completion_date }}', max_length=100)),
                ('certificate_id_display', models.CharField(default='{{ certificate_id }}', max_length=100)),
                ('instructor_signature_text', models.CharField(blank=True, max_length=255)),
                ('footer_note', models.TextField(blank=True)),
                ('completion_percentage', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('enable_verification', models.BooleanField(default=True)),
                ('show_qr_code', models.BooleanField(default=True)),
                ('show_certificate_id', models.BooleanField(default=True)),
                ('verification_url_format', models.CharField(blank=True, max_length=255)),
                ('expires', models.BooleanField(default=False)),
                ('validity_months', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='lms.course')),
            ],
            options={
                'ordering': ['course', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='quiz',
            name='pass_mark',
            field=models.SmallIntegerField(default=70, help_text='Percentage required to pass exam.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass Mark'),
        ),
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificates', to='lms.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.certificatetemplate')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_completed', models.BooleanField(default=False)),
                ('assessment_passed', models.BooleanField(default=False)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_quiz_taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_progress_records', to='lms.quiztaker')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='lms.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='lms.lmsprofile')),
            ],
            options={
                'ordering': ['module__order', 'module__id'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
