# Generated by Django 4.2.20 on 2026-05-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_coursemodule_skip_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='generated_for',
            field=models.ForeignKey(blank=True, help_text='When set, this quiz is personalized for one enrolled learner.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_quizzes', to='lms.lmsprofile'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', help_text='Tracks whether a personalized assessment is being prepared.', max_length=20),
        ),
    ]
