# Generated by Django 4.2.20 on 2026-06-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_dedupe_ai_module_quizzes_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='accent_color',
            field=models.CharField(default='#1FAA59', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='primary_color',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
    ]
