# Generated by Django 4.2.20 on 2026-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_lmsprofile_legal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
