# Generated by Django 4.2.20 on 2026-06-06 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_alter_quiz_slug_alter_quiz_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('force', models.BooleanField(default=False)),
                ('question_count', models.PositiveIntegerField(default=5)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error', models.TextField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_jobs', to='lms.coursemodule')),
            ],
            options={
                'verbose_name': 'Quiz Generation Job',
                'verbose_name_plural': 'Quiz Generation Jobs',
                'ordering': ['-force', 'created_at'],
            },
        ),
    ]
