# Generated by Django 4.2.20 on 2026-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0027_quizgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='True if this quiz was generated by Cerebras AI (not fallback/manual).'),
        ),
    ]
