# Generated by Django 4.2.20 on 2026-06-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_quiz_ai_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the course was created', null=True),
        ),
    ]
