# Generated by Django 4.2.20 on 2026-06-25 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0029_course_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='certificate_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this certificate in TZS. Leave blank to use the default (15,000 TZS).', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CertificatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippe_session_id', models.CharField(blank=True, default='', help_text='Snippe session reference', max_length=100)),
                ('snippe_reference', models.CharField(blank=True, default='', help_text='Snippe payment reference from webhook', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('checkout_url', models.URLField(blank=True, default='', help_text='Snippe hosted checkout URL')),
                ('payment_link_url', models.URLField(blank=True, default='', help_text='Short payment link URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.studentcertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate Payment',
                'verbose_name_plural': 'Certificate Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
