# Generated by Django 5.2 on 2026-07-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_certificatepayment_webhook_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippe_session_id', models.CharField(blank=True, default='', help_text='Snippe session reference', max_length=100)),
                ('snippe_reference', models.CharField(blank=True, default='', help_text='Snippe payment reference from webhook', max_length=100)),
                ('webhook_event_id', models.CharField(blank=True, default='', help_text='Snippe webhook event ID (idempotency key)', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Failure reason from Snippe')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('checkout_url', models.URLField(blank=True, default='', help_text='Snippe hosted checkout URL')),
                ('payment_link_url', models.URLField(blank=True, default='', help_text='Short payment link URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Payment',
                'verbose_name_plural': 'Course Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
