# Generated by Django 4.2.20 on 2026-07-08 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0032_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='admin_granted_access',
            field=models.BooleanField(default=False, help_text='Admin has granted course access without payment. Certificate access is not included.'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='admin_granted_certificate',
            field=models.BooleanField(default=False, help_text='Admin has granted certificate access in addition to course access.'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
