# Generated by Django 4.2.20 on 2026-08-03 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0033_courseenrollment_admin_granted_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Admin who granted this module access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_access_grants_granted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='lms.coursemodule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_grants', to='lms.lmsprofile')),
            ],
            options={
                'verbose_name': 'Module Access Grant',
                'verbose_name_plural': 'Module Access Grants',
                'ordering': ['-granted_at'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
