# Generated by Django 4.2.20 on 2026-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_moduleaccessgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='certificate_prepaid',
            field=models.BooleanField(default=False, help_text='Certificate has been prepaid as part of this enrollment.'),
        ),
    ]
