# Generated by Django 4.2.20 on 2026-08-08 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0035_courseenrollment_certificate_prepaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (TZS) for single-module access. Leave empty to hide the Request Access option.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ModulePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippe_session_id', models.CharField(blank=True, default='', help_text='Snippe session reference', max_length=100)),
                ('snippe_reference', models.CharField(blank=True, default='', help_text='Snippe payment reference from webhook', max_length=100)),
                ('webhook_event_id', models.CharField(blank=True, default='', help_text='Snippe webhook event ID (idempotency key)', max_length=100)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Failure reason from Snippe')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('checkout_url', models.URLField(blank=True, default='', help_text='Snippe hosted checkout URL')),
                ('payment_link_url', models.URLField(blank=True, default='', help_text='Short payment link URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms.coursemodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Payment',
                'verbose_name_plural': 'Module Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_access_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='lms.coursemodule')),
                ('payment', models.ForeignKey(blank=True, help_text='The completed Snippe payment behind this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_request', to='lms.modulepayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access_requests', to='lms.lmsprofile')),
            ],
            options={
                'verbose_name': 'Module Access Request',
                'verbose_name_plural': 'Module Access Requests',
                'ordering': ['-requested_at'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
