# Generated by Django 4.2.20 on 2026-08-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_auto_approve_paid_module_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='show_list_ads',
            field=models.BooleanField(default=True, help_text='When enabled, ads are inserted into product, course, blog, and materials list pages.', verbose_name='Show List Ads'),
        ),
    ]
