# Generated by Django 4.2.20 on 2026-08-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_alter_sitesettings_show_list_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_ads_before_free_courses',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_list_ads',
        ),
    ]
