# Generated by Django 5.2.17 on 2026-09-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_snippewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='admin_override_completion',
            field=models.BooleanField(default=False, help_text='Admin has overridden course completion. Student must pay for certificate but completion is not auto-issued.'),
        ),
    ]
