# Generated by Django 5.2.17 on 2026-10-01 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_courseenrollment_admin_override_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='watermark_opacity',
            field=models.FloatField(blank=True, default=0.15, help_text="Faded seal strength behind the certificate text (0.08-0.30). Measured on a 300dpi print render: below 0.08 the seal drops under the ~14/255 level most printers clip and vanishes on paper, while above 0.30 it starts costing contrast on the recipient's name. 0.15 prints at 36/255 and keeps text at 11:1 contrast.", validators=[django.core.validators.MinValueValidator(0.08), django.core.validators.MaxValueValidator(0.30)]),
        ),
    ]
